// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestHeartBeat.proto

package com.github.quantranuk.protobuf.nio.proto;

public final class TestHeartBeat {
  private TestHeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.quantran.protobuf.nio.proto.HeartBeatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestTimeMillis = 1;</code>
     */
    long getRequestTimeMillis();

    /**
     * <code>string requestMessage = 2;</code>
     */
    String getRequestMessage();
    /**
     * <code>string requestMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getRequestMessageBytes();
  }
  /**
   * Protobuf type {@code com.quantran.protobuf.nio.proto.HeartBeatRequest}
   */
  public  static final class HeartBeatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.quantran.protobuf.nio.proto.HeartBeatRequest)
      HeartBeatRequestOrBuilder {
    // Use HeartBeatRequest.newBuilder() to construct.
    private HeartBeatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatRequest() {
      requestTimeMillis_ = 0L;
      requestMessage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeartBeatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestTimeMillis_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              requestMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestHeartBeat.HeartBeatRequest.class, TestHeartBeat.HeartBeatRequest.Builder.class);
    }

    public static final int REQUESTTIMEMILLIS_FIELD_NUMBER = 1;
    private long requestTimeMillis_;
    /**
     * <code>int64 requestTimeMillis = 1;</code>
     */
    public long getRequestTimeMillis() {
      return requestTimeMillis_;
    }

    public static final int REQUESTMESSAGE_FIELD_NUMBER = 2;
    private volatile Object requestMessage_;
    /**
     * <code>string requestMessage = 2;</code>
     */
    public String getRequestMessage() {
      Object ref = requestMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        requestMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string requestMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMessageBytes() {
      Object ref = requestMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestTimeMillis_ != 0L) {
        output.writeInt64(1, requestTimeMillis_);
      }
      if (!getRequestMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestTimeMillis_);
      }
      if (!getRequestMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestHeartBeat.HeartBeatRequest)) {
        return super.equals(obj);
      }
      TestHeartBeat.HeartBeatRequest other = (TestHeartBeat.HeartBeatRequest) obj;

      boolean result = true;
      result = result && (getRequestTimeMillis()
          == other.getRequestTimeMillis());
      result = result && getRequestMessage()
          .equals(other.getRequestMessage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTimeMillis());
      hash = (37 * hash) + REQUESTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestHeartBeat.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestHeartBeat.HeartBeatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.quantran.protobuf.nio.proto.HeartBeatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.quantran.protobuf.nio.proto.HeartBeatRequest)
        TestHeartBeat.HeartBeatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestHeartBeat.HeartBeatRequest.class, TestHeartBeat.HeartBeatRequest.Builder.class);
      }

      // Construct using TestHeartBeat.HeartBeatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestTimeMillis_ = 0L;

        requestMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor;
      }

      public TestHeartBeat.HeartBeatRequest getDefaultInstanceForType() {
        return TestHeartBeat.HeartBeatRequest.getDefaultInstance();
      }

      public TestHeartBeat.HeartBeatRequest build() {
        TestHeartBeat.HeartBeatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestHeartBeat.HeartBeatRequest buildPartial() {
        TestHeartBeat.HeartBeatRequest result = new TestHeartBeat.HeartBeatRequest(this);
        result.requestTimeMillis_ = requestTimeMillis_;
        result.requestMessage_ = requestMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestHeartBeat.HeartBeatRequest) {
          return mergeFrom((TestHeartBeat.HeartBeatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestHeartBeat.HeartBeatRequest other) {
        if (other == TestHeartBeat.HeartBeatRequest.getDefaultInstance()) return this;
        if (other.getRequestTimeMillis() != 0L) {
          setRequestTimeMillis(other.getRequestTimeMillis());
        }
        if (!other.getRequestMessage().isEmpty()) {
          requestMessage_ = other.requestMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestHeartBeat.HeartBeatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestHeartBeat.HeartBeatRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestTimeMillis_ ;
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public long getRequestTimeMillis() {
        return requestTimeMillis_;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public Builder setRequestTimeMillis(long value) {
        
        requestTimeMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public Builder clearRequestTimeMillis() {
        
        requestTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private Object requestMessage_ = "";
      /**
       * <code>string requestMessage = 2;</code>
       */
      public String getRequestMessage() {
        Object ref = requestMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          requestMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string requestMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMessageBytes() {
        Object ref = requestMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestMessage = 2;</code>
       */
      public Builder setRequestMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestMessage = 2;</code>
       */
      public Builder clearRequestMessage() {
        
        requestMessage_ = getDefaultInstance().getRequestMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string requestMessage = 2;</code>
       */
      public Builder setRequestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.quantran.protobuf.nio.proto.HeartBeatRequest)
    }

    // @@protoc_insertion_point(class_scope:com.quantran.protobuf.nio.proto.HeartBeatRequest)
    private static final TestHeartBeat.HeartBeatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestHeartBeat.HeartBeatRequest();
    }

    public static TestHeartBeat.HeartBeatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatRequest>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatRequest>() {
      public HeartBeatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HeartBeatRequest> getParserForType() {
      return PARSER;
    }

    public TestHeartBeat.HeartBeatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.quantran.protobuf.nio.proto.HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestTimeMillis = 1;</code>
     */
    long getRequestTimeMillis();

    /**
     * <code>int64 responseTimeMillis = 2;</code>
     */
    long getResponseTimeMillis();

    /**
     * <code>string responseMessage = 3;</code>
     */
    String getResponseMessage();
    /**
     * <code>string responseMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code com.quantran.protobuf.nio.proto.HeartBeatResponse}
   */
  public  static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.quantran.protobuf.nio.proto.HeartBeatResponse)
      HeartBeatResponseOrBuilder {
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatResponse() {
      requestTimeMillis_ = 0L;
      responseTimeMillis_ = 0L;
      responseMessage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeartBeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestTimeMillis_ = input.readInt64();
              break;
            }
            case 16: {

              responseTimeMillis_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestHeartBeat.HeartBeatResponse.class, TestHeartBeat.HeartBeatResponse.Builder.class);
    }

    public static final int REQUESTTIMEMILLIS_FIELD_NUMBER = 1;
    private long requestTimeMillis_;
    /**
     * <code>int64 requestTimeMillis = 1;</code>
     */
    public long getRequestTimeMillis() {
      return requestTimeMillis_;
    }

    public static final int RESPONSETIMEMILLIS_FIELD_NUMBER = 2;
    private long responseTimeMillis_;
    /**
     * <code>int64 responseTimeMillis = 2;</code>
     */
    public long getResponseTimeMillis() {
      return responseTimeMillis_;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 3;
    private volatile Object responseMessage_;
    /**
     * <code>string responseMessage = 3;</code>
     */
    public String getResponseMessage() {
      Object ref = responseMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      Object ref = responseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestTimeMillis_ != 0L) {
        output.writeInt64(1, requestTimeMillis_);
      }
      if (responseTimeMillis_ != 0L) {
        output.writeInt64(2, responseTimeMillis_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, responseMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestTimeMillis_);
      }
      if (responseTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, responseTimeMillis_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, responseMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestHeartBeat.HeartBeatResponse)) {
        return super.equals(obj);
      }
      TestHeartBeat.HeartBeatResponse other = (TestHeartBeat.HeartBeatResponse) obj;

      boolean result = true;
      result = result && (getRequestTimeMillis()
          == other.getRequestTimeMillis());
      result = result && (getResponseTimeMillis()
          == other.getResponseTimeMillis());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestTimeMillis());
      hash = (37 * hash) + RESPONSETIMEMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResponseTimeMillis());
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestHeartBeat.HeartBeatResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestHeartBeat.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestHeartBeat.HeartBeatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.quantran.protobuf.nio.proto.HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.quantran.protobuf.nio.proto.HeartBeatResponse)
        TestHeartBeat.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestHeartBeat.HeartBeatResponse.class, TestHeartBeat.HeartBeatResponse.Builder.class);
      }

      // Construct using TestHeartBeat.HeartBeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestTimeMillis_ = 0L;

        responseTimeMillis_ = 0L;

        responseMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestHeartBeat.internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor;
      }

      public TestHeartBeat.HeartBeatResponse getDefaultInstanceForType() {
        return TestHeartBeat.HeartBeatResponse.getDefaultInstance();
      }

      public TestHeartBeat.HeartBeatResponse build() {
        TestHeartBeat.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestHeartBeat.HeartBeatResponse buildPartial() {
        TestHeartBeat.HeartBeatResponse result = new TestHeartBeat.HeartBeatResponse(this);
        result.requestTimeMillis_ = requestTimeMillis_;
        result.responseTimeMillis_ = responseTimeMillis_;
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestHeartBeat.HeartBeatResponse) {
          return mergeFrom((TestHeartBeat.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestHeartBeat.HeartBeatResponse other) {
        if (other == TestHeartBeat.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.getRequestTimeMillis() != 0L) {
          setRequestTimeMillis(other.getRequestTimeMillis());
        }
        if (other.getResponseTimeMillis() != 0L) {
          setResponseTimeMillis(other.getResponseTimeMillis());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestHeartBeat.HeartBeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestHeartBeat.HeartBeatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestTimeMillis_ ;
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public long getRequestTimeMillis() {
        return requestTimeMillis_;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public Builder setRequestTimeMillis(long value) {
        
        requestTimeMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestTimeMillis = 1;</code>
       */
      public Builder clearRequestTimeMillis() {
        
        requestTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private long responseTimeMillis_ ;
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       */
      public long getResponseTimeMillis() {
        return responseTimeMillis_;
      }
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       */
      public Builder setResponseTimeMillis(long value) {
        
        responseTimeMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 responseTimeMillis = 2;</code>
       */
      public Builder clearResponseTimeMillis() {
        
        responseTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 3;</code>
       */
      public String getResponseMessage() {
        Object ref = responseMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder setResponseMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 3;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.quantran.protobuf.nio.proto.HeartBeatResponse)
    }

    // @@protoc_insertion_point(class_scope:com.quantran.protobuf.nio.proto.HeartBeatResponse)
    private static final TestHeartBeat.HeartBeatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestHeartBeat.HeartBeatResponse();
    }

    public static TestHeartBeat.HeartBeatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatResponse>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    public TestHeartBeat.HeartBeatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017HeartBeat.proto\022\034org.quantran.tools.sb" +
      "m.proto\"E\n\020HeartBeatRequest\022\031\n\021requestTi" +
      "meMillis\030\001 \001(\003\022\026\n\016requestMessage\030\002 \001(\t\"c" +
      "\n\021HeartBeatResponse\022\031\n\021requestTimeMillis" +
      "\030\001 \001(\003\022\032\n\022responseTimeMillis\030\002 \001(\003\022\027\n\017re" +
      "sponseMessage\030\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_quantran_tools_sbm_proto_HeartBeatRequest_descriptor,
        new String[] { "RequestTimeMillis", "RequestMessage", });
    internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_quantran_tools_sbm_proto_HeartBeatResponse_descriptor,
        new String[] { "RequestTimeMillis", "ResponseTimeMillis", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
